ORG 0100H
START:
    MOV SP,#3FH
    CLR EA
    MOV TMOD,#20H
    MOV SCON,#50H
    MOV TH1,#0FDH
    MOV TL1,#0FDH
    SETB TR1

    MOV R7,#00H
    MOV P2,#3FH
    CLR P3.7
    SETB P3.2

MAIN_LOOP:
    JNB RI, MAIN_LOOP
    MOV A, SBUF
    CLR RI

CHK_PLUS:
    CJNE A,#2BH, CHK_MINUS
    INC R7
    CJNE R7,#0AH, SHOW_SEG
    MOV R7,#00H
    SJMP SHOW_SEG

CHK_MINUS:
    CJNE A,#2DH, CHK_ZERO
    CJNE R7,#00H, DEC_OK
    MOV R7,#09H
    SJMP SHOW_SEG
DEC_OK:
    DEC R7
SHOW_SEG:
    MOV A, R7
    ACALL DISPLAY
    LJMP MAIN_LOOP

CHK_ZERO:
    CJNE A,#30H, CHK_NUM_BLINK
    LJMP MAIN_LOOP

CHK_NUM_BLINK:
    CLR C
    MOV R2, A
    SUBB A, #31H
    JC NOT_NUM
    MOV A, R2
    SUBB A, #3AH
    JNC NOT_NUM

    MOV A, R2
    ANL A, #0FH
    MOV R5, A

BLINK_LOOP:
    SETB P3.2
    SETB P3.7
    ACALL DELAY
    CLR P3.7
    ACALL DELAY
    DJNZ R5, BLINK_LOOP
    LJMP MAIN_LOOP

NOT_NUM:
    CLR P3.2
    MOV A,#0AH
    CLR P3.7
    LJMP MAIN_LOOP

DISPLAY:
    MOV DPTR,#SEG_TAB
    MOVC A,@A+DPTR
    MOV P2,A
    RET

DELAY:
    MOV R4,#2
D0: MOV R2,#200
D1: MOV R3,#255
D2: DJNZ R3,D2
    DJNZ R2,D1
    DJNZ R4,D0
    RET

SEG_TAB:
    DB 3FH,06H,5BH,4FH,66H,6DH,7DH,07H,7FH,6FH

END